from asyncio import Protocol

from app.schemas.ItemSchemas import ItemCreate, ItemUpdate


class ItemsService(Protocol):
    async def get_items(self, user_id: int) -> list[dict]: ...
    async def get_item(self, item_id: int, user_id: int) -> dict | None: ...
    async def create_item(self, item_create: ItemCreate) -> dict: ...
    async def update_item(
        self, item_id: int, item_update: ItemUpdate
    ) -> dict | None: ...
    async def delete_item(self, item_id: int) -> bool: ...
